name: goreleaser

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Note'
        required: false
        default: ''
  pull_request:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.2
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lbcwallet-${{ github.sha }}
          path: |
            dist/checksums.txt
            dist/*.tar.gz
